# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 6 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
baseurl: /
url: htttp://betajippity.github.io
permalink: /:year/:month/:title.html
author: Yining Karl Li
authorurl: http://www.yiningkarlli.com
name: Code &#38; Visuals
